/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package corretordeprovas.view;

/**
 *
 * @author romulo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setSize(800,600);
        setResizable(false);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonProvas = new javax.swing.JButton();
        jButtonCorrecoes = new javax.swing.JButton();
        jButtonTurmas = new javax.swing.JButton();
        jButtonResultados = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonProvas.setBackground(new java.awt.Color(0, 0, 128));
        jButtonProvas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonProvas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonProvas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corretordeprovas/imagens/provas 128.png"))); // NOI18N
        jButtonProvas.setText("Provas");
        getContentPane().add(jButtonProvas);
        jButtonProvas.setBounds(290, 50, 270, 200);

        jButtonCorrecoes.setBackground(new java.awt.Color(212, 0, 0));
        jButtonCorrecoes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCorrecoes.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCorrecoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corretordeprovas/imagens/corrigir2 128.png"))); // NOI18N
        jButtonCorrecoes.setText("Correções");
        getContentPane().add(jButtonCorrecoes);
        jButtonCorrecoes.setBounds(10, 260, 270, 200);

        jButtonTurmas.setBackground(new java.awt.Color(255, 82, 115));
        jButtonTurmas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonTurmas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTurmas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corretordeprovas/imagens/turmas 128.png"))); // NOI18N
        jButtonTurmas.setText("Turmas");
        getContentPane().add(jButtonTurmas);
        jButtonTurmas.setBounds(10, 50, 270, 200);

        jButtonResultados.setBackground(new java.awt.Color(0, 153, 51));
        jButtonResultados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonResultados.setForeground(new java.awt.Color(255, 255, 255));
        jButtonResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corretordeprovas/imagens/estatisticas 128.png"))); // NOI18N
        jButtonResultados.setText("Resultados");
        getContentPane().add(jButtonResultados);
        jButtonResultados.setBounds(290, 260, 270, 200);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corretordeprovas/imagens/fundo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -40, 800, 620);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 204));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corretordeprovas/imagens/home.png"))); // NOI18N
        jMenu5.setText("Home");
        jMenu5.setActionCommand("");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu5);

        jMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corretordeprovas/imagens/turmas 32.png"))); // NOI18N
        jMenu1.setText("Turmas");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corretordeprovas/imagens/provas 32.png"))); // NOI18N
        jMenu2.setText("Provas");
        jMenu2.setToolTipText("");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corretordeprovas/imagens/corrigir2 32.png"))); // NOI18N
        jMenu3.setText("Correções");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corretordeprovas/imagens/estatisticas 32.png"))); // NOI18N
        jMenu4.setText("Resultados");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCorrecoes;
    private javax.swing.JButton jButtonProvas;
    private javax.swing.JButton jButtonResultados;
    private javax.swing.JButton jButtonTurmas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
